@baseUri = http://localhost:7071
@id = 4a491024-9970-4f48-942e-863254947e8d
@id2 = cb684952-fba4-47cb-bf9a-6b8b683c27f5
@logicAppEmailUrl = https://get-this-from-user-secrets-file.com

### Get ALL Menu items
GET {{baseUri}}/api/menu-items

### Get Menu item
GET {{baseUri}}/api/menu-items/{{id}}

### Insert item
POST {{baseUri}}/api/menu-items

{
    "name": "Blackened Chicken",
    "description": "Description description ",
    "carbs": 50,
    "protein": 40,
    "fat": 30,
    "calories": 60,
    "imageUrl": "/chicken.jpg",
    "category": "meal",
    "price": 5.00
}

### Update item
PUT {{baseUri}}/api/menu-items/{{id}}

{
    "id": "{{id}}",
    "name": "Honey Mustard Chicken",
    "description": "updated tosaoetutaohuntoaehut",
    "carbs": 50,
    "protein": 40,
    "fat": 30,
    "calories": 60,
    "imageUrl": "/chicken.jpg",
    "category": "meal",
    "price": 5.00
}

### DELETE item

DELETE {{baseUri}}/api/menu-items/{{id}}


### Get Customer Menu
GET {{baseUri}}/api/customer/current-menu


### Insert new Customer Order
POST {{baseUri}}/api/customer/order

{
    "lineItems": [
      { "menuItemId": "111", "name": "Honey Chicken", "quantity": 1, "price": 5, "subTotal": 5 },
      { "menuItemId": "222", "name": "Buffalo Chicken", "quantity": 3, "price": 4, "subTotal": 12 },
      { "menuItemId": "333", "name": "Energy Balls", "quantity": 2, "price": 3.5, "subTotal": 10.5 }
    ],
    "grandTotal": 27.5,
    "fullName": "Bob Smith",
    "email": "steve.michelotti@gmail.com",
    "venmoHandle": "bobsmithiscool",
    "distributionMethod": "delivery",
    "streetAddress": "123 Main Street",
    "city": "Baltimore",
    "zipCode": "22222"
}

### Get ALL Order
GET {{baseUri}}/api/orders


### Update order status
PUT {{baseUri}}/api/orders/{{id}}/status

{
  "orderStatus": 1
}

### Insert new Menu
POST {{baseUri}}/api/menus

{
  "name": "feb 2 menu",
  "startTime": "2021-02-01T12:00:00",
  "endTime": "2021-02-05T12:00:00",
  "menuItemIds": [ "ntaoehuntaeohu", "bbb", "ccc" ]
}

### Get Menu
GET {{baseUri}}/api/menus/{{id2}}

### Get ALL Menus
GET {{baseUri}}/api/menus

### Update menu
PUT {{baseUri}}/api/menus/{{id2}}

{
  "id": "{{id2}}",
  "name": "feb 21110 menu",
  "startTime": "2021-02-01T12:00:00",
  "endTime": "2021-02-05T12:00:00",
  "menuItemIds": [ "test", "bbb", "ccc" ]
}


### Confirmation email

POST {{logicAppEmailUrl}}
Content-Type: application/json

{
  "email": "steve.michelotti@gmail.com",
  "message": "this is a test message",
  "orderId": "123"
}