@baseUri = http://localhost:7071
@id = 5e2703cd-a271-4051-9b4b-edeae52398c0

### Get ALL Menu items
GET {{baseUri}}/api/menu-items

### Get Menu item
GET {{baseUri}}/api/menu-items/{{id}}

### Insert item
POST {{baseUri}}/api/menu-items

{
    "name": "Blackened Chicken",
    "description": "Description description ",
    "carbs": 50,
    "protein": 40,
    "fat": 30,
    "calories": 60,
    "imageUrl": "/chicken.jpg",
    "category": "meal",
    "price": 5.00
}

### Update item
PUT {{baseUri}}/api/menu-items/{{id}}

{
    "id": "{{id}}",
    "name": "Honey Mustard Chicken",
    "description": "updated tosaoetutaohuntoaehut",
    "carbs": 50,
    "protein": 40,
    "fat": 30,
    "calories": 60,
    "imageUrl": "/chicken.jpg",
    "category": "meal",
    "price": 5.00
}

### DELETE item

DELETE {{baseUri}}/api/menu-items/{{id}}


### Insert new Customer Order
POST {{baseUri}}/api/customer/order

{
    "lineItems": [
      { menuItemId: "111", quantity: 1, subTotal: 5 },
      { menuItemId: "222", quantity: 3, subTotal: 15 },
      { menuItemId: "333", quantity: 5, subTotal: 25.5 }
    ],
    "grandTotal": 45.5,
    "fullName": "Bob Smith",
    "email": "bob.smith@gmail.com",
    "venmoHandle": "bobsmithiscool",
    "distributionMethod": "delivery",
    "streetAddress": "123 Main Street",
    "city": "Baltimore",
    "zipCode": "22222"
}

### Get ALL Order
GET {{baseUri}}/api/orders
